### ISSUE TITLE
reset/regenerate waypoints and markers at start

### ISSUE THREAD

**Issue by pqnet** [Arsonide/FinePrint#15]
Sometimes the game, for reason unrelated to the mod, crashes leaving the contract system in an inconsistent state. When restarting all the currently active contracts and the contract history are reset, this is pretty frustrating but can't be helped. When that happens, FinePrint waypoints and markers are left in the tracking station (strangely enough they don't appear in the map view while piloting a vehicle). Since this kind of crash is happening pretty often (I think it is related to switching vessels by double click from map view) the tracking station becomes so cluttered it is unplayable.

Would it be possible to remove all markers and waypoints when the game is loaded, and re-create them based on the currently active contracts? This should work around the bug, and any eventual opposite bugs in which some waypoint is not created correctly when a mission is accepted.

**Comment by Arsonide** [comment]
This is not an issue, this is how the mod behaves. The game _does_ reset all waypoints when the scene changes, but, in the tracking station, all currently existing contracts are shown, even contracts you have not accepted yet.

This is a feature that was requested, so that people could see where a contract is, or what an orbit looks like, before they accept a contract.

The next version will have a toolbar icon that lets you disable waypoints for "offered" but not accepted contracts in the tracking station. I have this working on my local repository, but haven't committed it to the develop branch quite yet.

**Comment by pqnet** [comment]
my mistake then I think. Sorry
